const WORDS = [
  {
    term: "model",
    translation: "模型",
    category: "AI 入门",
    difficulty: "beginner",
    meaning: "在 AI 中，model 是从数据中学习规律后，用来做预测、生成或判断的系统。",
    simple: "可以把它理解成已经学过经验的“判断器”或“生成器”。",
    example: "The model predicts whether an email is spam.",
    exampleZh: "这个模型预测一封邮件是否是垃圾邮件。",
    confusion: "model 不是代码本身，也不是数据本身，而是训练后得到的能力载体。",
    related: ["training", "inference", "parameter"]
  },
  {
    term: "training",
    translation: "训练",
    category: "AI 入门",
    difficulty: "beginner",
    meaning: "让模型通过大量数据调整内部参数，从而学会完成某类任务的过程。",
    simple: "像给模型做大量练习题，并根据答案不断调整。",
    example: "Training requires a large labeled dataset.",
    exampleZh: "训练需要大量带标签的数据集。",
    confusion: "training 是学习阶段，inference 是使用模型阶段。",
    related: ["dataset", "label", "parameter"]
  },
  {
    term: "inference",
    translation: "推理 / 使用模型",
    category: "AI 入门",
    difficulty: "beginner",
    meaning: "模型训练完成后，接收新输入并给出输出的过程。",
    simple: "模型已经学完了，现在拿来实际回答问题或做预测。",
    example: "During inference, the model generates a response token by token.",
    exampleZh: "在推理阶段，模型逐个 token 生成回答。",
    confusion: "中文“推理”容易让人以为是逻辑推理，但 AI 文档里常指运行模型得到结果。",
    related: ["prediction", "generation", "model"]
  },
  {
    term: "dataset",
    translation: "数据集",
    category: "AI 入门",
    difficulty: "beginner",
    meaning: "用于训练、验证或测试模型的一组数据。",
    simple: "模型学习和考试用的题库。",
    example: "The dataset contains images and labels.",
    exampleZh: "这个数据集包含图片和标签。",
    confusion: "dataset 不等于 database；它更强调用于机器学习任务的数据集合。",
    related: ["label", "training", "benchmark"]
  },
  {
    term: "label",
    translation: "标签",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "监督学习中给数据标注的正确答案或目标结果。",
    simple: "告诉模型这道题的标准答案是什么。",
    example: "Each image has a label such as cat or dog.",
    exampleZh: "每张图片都有一个标签，比如猫或狗。",
    confusion: "label 通常是答案，feature 通常是输入特征。",
    related: ["feature", "supervised learning", "classification"]
  },
  {
    term: "feature",
    translation: "特征",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "模型用于判断或预测的输入信息。",
    simple: "模型看题时能看到的线索。",
    example: "House size is an important feature for price prediction.",
    exampleZh: "房屋面积是预测房价的重要特征。",
    confusion: "feature 是输入线索，label 是模型要预测的答案。",
    related: ["label", "regression", "dataset"]
  },
  {
    term: "parameter",
    translation: "参数",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "模型在训练过程中自动学到的内部数值。",
    simple: "模型脑子里被训练调整出来的数值。",
    example: "Large language models have billions of parameters.",
    exampleZh: "大语言模型有数十亿个参数。",
    confusion: "parameter 是模型学出来的，hyperparameter 通常是人提前设置的。",
    related: ["hyperparameter", "training", "model"]
  },
  {
    term: "hyperparameter",
    translation: "超参数",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "训练前由人设置，用来控制训练过程或模型结构的配置。",
    simple: "不是模型自己学的，而是你先给训练过程定的规则。",
    example: "Learning rate is a common hyperparameter.",
    exampleZh: "学习率是常见的超参数。",
    confusion: "不要和 parameter 混淆；parameter 是训练学到的。",
    related: ["learning rate", "parameter", "epoch"]
  },
  {
    term: "loss",
    translation: "损失",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "衡量模型预测结果和正确答案之间差距的数值。",
    simple: "模型做题错得有多离谱的分数。",
    example: "The goal of training is to minimize the loss.",
    exampleZh: "训练的目标是让损失尽可能小。",
    confusion: "loss 越低通常越好，但低训练损失不一定代表泛化能力好。",
    related: ["optimizer", "gradient", "overfitting"]
  },
  {
    term: "gradient",
    translation: "梯度",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "指示参数应该朝哪个方向调整，才能让损失变小的信息。",
    simple: "告诉模型往哪里改，错得会少一点。",
    example: "The optimizer updates parameters using gradients.",
    exampleZh: "优化器使用梯度更新参数。",
    confusion: "gradient 不是最终答案，而是更新参数的方向和幅度线索。",
    related: ["optimizer", "backpropagation", "loss"]
  },
  {
    term: "optimizer",
    translation: "优化器",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "根据梯度更新模型参数的算法。",
    simple: "负责帮模型改参数的工具。",
    example: "Adam is a widely used optimizer.",
    exampleZh: "Adam 是一种广泛使用的优化器。",
    confusion: "optimizer 不直接做预测，它负责训练时如何更新模型。",
    related: ["gradient", "learning rate", "training"]
  },
  {
    term: "epoch",
    translation: "训练轮次",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "模型完整看完一遍训练数据，通常称为一个 epoch。",
    simple: "整本练习册刷完一遍。",
    example: "The model was trained for ten epochs.",
    exampleZh: "这个模型训练了十个轮次。",
    confusion: "epoch 不等于 batch；一个 epoch 里通常有很多 batch。",
    related: ["batch", "training", "dataset"]
  },
  {
    term: "batch",
    translation: "批次",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "训练时一次送入模型的一小组数据。",
    simple: "每次不刷完整本练习册，而是先刷一小摞题。",
    example: "A larger batch size needs more GPU memory.",
    exampleZh: "更大的批次大小需要更多 GPU 显存。",
    confusion: "batch size 是每批数据数量，不是训练总数据量。",
    related: ["epoch", "GPU", "training"]
  },
  {
    term: "overfitting",
    translation: "过拟合",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "模型过度记住训练数据细节，导致面对新数据表现变差。",
    simple: "把练习题背熟了，但换一道新题就不会了。",
    example: "Dropout can help reduce overfitting.",
    exampleZh: "Dropout 可以帮助减少过拟合。",
    confusion: "训练集表现好不代表模型真的学会了规律。",
    related: ["generalization", "dropout", "validation"]
  },
  {
    term: "generalization",
    translation: "泛化",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "模型把学到的规律应用到新数据上的能力。",
    simple: "不是只会做原题，而是会做同类型新题。",
    example: "Good generalization is important for real-world use.",
    exampleZh: "良好的泛化能力对真实场景使用很重要。",
    confusion: "generalization 强调新数据表现，不是训练集记忆能力。",
    related: ["overfitting", "test set", "validation"]
  },
  {
    term: "classification",
    translation: "分类",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "预测输入属于哪个类别的任务。",
    simple: "判断这东西是哪一类。",
    example: "Spam detection is a classification task.",
    exampleZh: "垃圾邮件检测是一个分类任务。",
    confusion: "classification 预测类别，regression 预测连续数值。",
    related: ["regression", "label", "accuracy"]
  },
  {
    term: "regression",
    translation: "回归",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "预测连续数值的任务，例如价格、温度或概率。",
    simple: "不是选类别，而是预测一个数字。",
    example: "Predicting house prices is a regression task.",
    exampleZh: "预测房价是一个回归任务。",
    confusion: "中文“回归”很抽象，在机器学习里常指预测连续值。",
    related: ["classification", "feature", "prediction"]
  },
  {
    term: "accuracy",
    translation: "准确率",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "预测正确的样本占全部样本的比例。",
    simple: "一共做了多少题，其中答对了多少。",
    example: "The classifier achieved 92% accuracy.",
    exampleZh: "这个分类器达到了 92% 的准确率。",
    confusion: "类别极不平衡时，accuracy 可能会误导。",
    related: ["precision", "recall", "classification"]
  },
  {
    term: "precision",
    translation: "精确率",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "模型预测为正例的样本中，真正为正例的比例。",
    simple: "模型说“是”的时候，有多少次真的说对了。",
    example: "High precision means fewer false positives.",
    exampleZh: "高精确率意味着更少误报。",
    confusion: "precision 关注预测为正的结果是否可靠，recall 关注正例有没有找全。",
    related: ["recall", "F1 score", "false positive"]
  },
  {
    term: "recall",
    translation: "召回率",
    category: "机器学习",
    difficulty: "beginner",
    meaning: "所有真正正例中，被模型找出来的比例。",
    simple: "该找出来的东西，模型找全了多少。",
    example: "Medical screening systems often need high recall.",
    exampleZh: "医疗筛查系统通常需要高召回率。",
    confusion: "recall 高不代表误报少，要和 precision 一起看。",
    related: ["precision", "F1 score", "false negative"]
  },
  {
    term: "neural network",
    translation: "神经网络",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "由多层计算单元组成，能够学习复杂模式的模型结构。",
    simple: "一层一层处理信息的 AI 模型结构。",
    example: "A neural network can learn patterns from images.",
    exampleZh: "神经网络可以从图片中学习模式。",
    confusion: "它受生物神经启发，但并不等同于人脑。",
    related: ["layer", "activation", "deep learning"]
  },
  {
    term: "activation",
    translation: "激活 / 激活函数",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "神经网络中引入非线性能力的函数或其输出。",
    simple: "让网络不只是做简单直线计算的关键开关。",
    example: "ReLU is a common activation function.",
    exampleZh: "ReLU 是常见的激活函数。",
    confusion: "activation 可能指函数，也可能指某层的输出值。",
    related: ["neural network", "layer", "ReLU"]
  },
  {
    term: "backpropagation",
    translation: "反向传播",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "从输出误差开始，反向计算各参数梯度的训练方法。",
    simple: "根据错在哪里，倒着追踪每个参数该怎么改。",
    example: "Backpropagation computes gradients efficiently.",
    exampleZh: "反向传播可以高效计算梯度。",
    confusion: "它不是模型预测步骤，而是训练时用于更新参数。",
    related: ["gradient", "loss", "optimizer"]
  },
  {
    term: "embedding",
    translation: "嵌入 / 向量表示",
    category: "大模型",
    difficulty: "beginner",
    meaning: "把文本、图片等对象转换成模型可以计算的向量表示。",
    simple: "把含义变成一串数字，让模型能比较和计算。",
    example: "Similar sentences have similar embeddings.",
    exampleZh: "相似的句子会有相似的嵌入向量。",
    confusion: "embedding 不是翻译结果，而是机器可计算的语义表示。",
    related: ["vector", "token", "semantic search"]
  },
  {
    term: "token",
    translation: "标记 / 令牌",
    category: "大模型",
    difficulty: "beginner",
    meaning: "模型处理文本时的基本单位，可以是字、词、子词或符号。",
    simple: "模型眼里的文字切片。",
    example: "The model has a context window of 128k tokens.",
    exampleZh: "这个模型的上下文窗口是 128k tokens。",
    confusion: "token 不一定等于 word；中文和英文的切分方式也不同。",
    related: ["tokenizer", "context window", "embedding"]
  },
  {
    term: "tokenizer",
    translation: "分词器",
    category: "大模型",
    difficulty: "beginner",
    meaning: "把文本切分成 token 的工具或算法。",
    simple: "负责把人类文字切成模型能吃的小块。",
    example: "The tokenizer converts text into token IDs.",
    exampleZh: "分词器把文本转换成 token 编号。",
    confusion: "tokenizer 不负责理解含义，只负责切分和编码。",
    related: ["token", "vocabulary", "context window"]
  },
  {
    term: "context window",
    translation: "上下文窗口",
    category: "大模型",
    difficulty: "beginner",
    meaning: "大模型一次能看到和处理的 token 数量范围。",
    simple: "模型当前能记在眼前的文本长度。",
    example: "A larger context window can handle longer documents.",
    exampleZh: "更大的上下文窗口可以处理更长的文档。",
    confusion: "上下文窗口大不等于模型一定更聪明，只是能容纳更多输入。",
    related: ["token", "prompt", "LLM"]
  },
  {
    term: "prompt",
    translation: "提示词 / 输入指令",
    category: "大模型",
    difficulty: "beginner",
    meaning: "用户给大模型的输入，用来引导模型生成目标输出。",
    simple: "你对模型说的话和交代的任务。",
    example: "A clear prompt improves the model's response.",
    exampleZh: "清晰的提示词可以改善模型回答。",
    confusion: "prompt 不只是问题，也可以包含背景、格式要求和示例。",
    related: ["instruction", "completion", "context window"]
  },
  {
    term: "completion",
    translation: "补全 / 生成结果",
    category: "大模型",
    difficulty: "beginner",
    meaning: "模型根据 prompt 继续生成的文本或结果。",
    simple: "你给开头，模型接着往下写。",
    example: "The API returns a completion for the prompt.",
    exampleZh: "API 会为这个提示词返回一个生成结果。",
    confusion: "在聊天模型里 completion 常对应 assistant 的回复。",
    related: ["prompt", "generation", "inference"]
  },
  {
    term: "LLM",
    translation: "大语言模型",
    category: "大模型",
    difficulty: "beginner",
    meaning: "Large Language Model 的缩写，指经过大量文本训练、能理解和生成语言的模型。",
    simple: "像 ChatGPT 这类能处理自然语言的大模型。",
    example: "An LLM can summarize, translate, and write code.",
    exampleZh: "大语言模型可以总结、翻译和写代码。",
    confusion: "LLM 是语言模型，不代表所有 AI 模型。",
    related: ["prompt", "token", "transformer"]
  },
  {
    term: "hallucination",
    translation: "幻觉",
    category: "大模型",
    difficulty: "beginner",
    meaning: "模型生成看似合理但实际上错误或没有依据的内容。",
    simple: "模型一本正经地胡说。",
    example: "RAG can reduce hallucination by grounding answers in documents.",
    exampleZh: "RAG 可以通过基于文档回答来减少幻觉。",
    confusion: "hallucination 不是模型有意识撒谎，而是生成机制导致的错误输出。",
    related: ["RAG", "grounding", "generation"]
  },
  {
    term: "RAG",
    translation: "检索增强生成",
    category: "大模型",
    difficulty: "beginner",
    meaning: "Retrieval-Augmented Generation，通过先检索资料再让模型生成回答的方法。",
    simple: "先查资料，再让模型带着资料回答。",
    example: "RAG is useful for question answering over private documents.",
    exampleZh: "RAG 适合基于私有文档做问答。",
    confusion: "RAG 通常不等于重新训练模型，而是给模型补充外部知识。",
    related: ["retrieval", "embedding", "vector database"]
  },
  {
    term: "agent",
    translation: "智能体",
    category: "大模型",
    difficulty: "beginner",
    meaning: "能根据目标规划步骤、调用工具并持续完成任务的 AI 系统。",
    simple: "不只回答问题，还能自己分步骤做事的 AI。",
    example: "An agent can search the web and summarize the results.",
    exampleZh: "智能体可以搜索网页并总结结果。",
    confusion: "agent 不是单个 prompt，而是一套带决策和工具调用的工作流程。",
    related: ["tool use", "planning", "function calling"]
  },
  {
    term: "fine-tuning",
    translation: "微调",
    category: "大模型",
    difficulty: "beginner",
    meaning: "在已有模型基础上，用特定数据继续训练，让模型更适应某类任务。",
    simple: "在通用能力上再做专项训练。",
    example: "Fine-tuning can adapt a model to a specific domain.",
    exampleZh: "微调可以让模型适应特定领域。",
    confusion: "fine-tuning 和 prompting 不同；前者改模型参数，后者改输入指令。",
    related: ["pretraining", "prompting", "parameter"]
  },
  {
    term: "alignment",
    translation: "对齐",
    category: "大模型",
    difficulty: "beginner",
    meaning: "让模型输出更符合人类意图、价值和安全要求的过程。",
    simple: "让模型更懂人想要什么，也更少乱来。",
    example: "Alignment helps models follow user instructions safely.",
    exampleZh: "对齐帮助模型安全地遵循用户指令。",
    confusion: "alignment 不是简单翻译成“排整齐”，它强调目标和行为一致。",
    related: ["instruction tuning", "RLHF", "safety"]
  },
  {
    term: "transformer",
    translation: "Transformer 架构",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "一种基于 attention 机制的神经网络架构，是许多大语言模型的基础。",
    simple: "现代大模型常用的核心网络结构。",
    example: "Most modern LLMs are based on the Transformer architecture.",
    exampleZh: "大多数现代大语言模型都基于 Transformer 架构。",
    confusion: "transformer 在 AI 里通常不是“变压器”的日常含义。",
    related: ["attention", "LLM", "token"]
  },
  {
    term: "attention",
    translation: "注意力机制",
    category: "深度学习",
    difficulty: "beginner",
    meaning: "让模型在处理信息时动态关注输入中更相关部分的机制。",
    simple: "模型读一句话时，决定哪些词更值得关注。",
    example: "Self-attention connects each token with other tokens in the sequence.",
    exampleZh: "自注意力会把序列中的每个 token 和其他 token 联系起来。",
    confusion: "AI 里的 attention 是计算机制，不是人的主观注意力。",
    related: ["self-attention", "transformer", "token"]
  }
];
